# Generated by Django 4.2 on 2024-01-08 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0002_employee_emarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='eNo',
            field=models.IntegerField(),
        ),
    ]
